services:
  dashboard:
    image: b4bz/homer
    container_name: dashboard
    volumes:
      - ./config:/www/assets # Make sure your local config directory exists
    ports:
      - 6001:8080
    user: 1000:1000
    environment:
      - INIT_ASSETS=1
    restart: unless-stopped
