---
title: "Dashboard"
# subtitle: "Applications & Links"
documentTitle: "Dashboard | Frustrated Functor"
icon: "fa-solid fa-ghost"

header: true
footer: false

layout: list
columns: "3"
connectivityCheck: true 

defaults:
  layout: columns
  colorTheme: auto

theme: walkxcode

links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/aloussase"

services:
  - name: "Latam"
    icon: "fa-solid fa-plane"
    items:
      - name: "GitLab"
        icon: "fa-brands fa-gitlab"
        subtitle: 'Source code repository'
        url: "https://gitlab.com/"
      - name: "Jira"
        icon: "fa-brands fa-jira"
        subtitle: 'Project management'
        url: 'https://projectmanagement.appslatam.com/secure/RapidBoard.jspa?rapidView=3740#'
      - name: "Confluence"
        icon: "fa-brands fa-confluence"
        subtitle: 'Squad documentation'
        url: 'https://docsrepo.appslatam.com/spaces/ELOE2E/pages/512688966/P%C3%A1gina+de+inicio+de+eLoyalty+-+E2E'
      - name: "AEM"
        icon: "fa-solid fa-file"
        subtitle: "Adobe Experience Manager"
        url: "https://author-latam-b75-stage3.adobecqms.net/libs/granite/core/content/login.html?resource=%2Feditor.html%2Fcontent%2Fdam%2Feffp%2Flatampass%2Fpt_br%2Fbanners%2Fcampaigns%2Famazon-com-br%2Famazon-com-br&$$login$$=%24%24login%24%24&j_reason=unknown&j_reason_code=unknown"
      - name: "App test users"
        icon: "fa-solid fa-user"
        subtitle: "List of test users for the app"
        url: "https://docs.google.com/spreadsheets/d/1HBqham5jsud7_IhJmjB4KoJzUvUmRHASfUv31RSvyNQ/edit?pli=1&gid=0#gid=0"

  - name: "Thesis"
    icon: 'fa-solid fa-graduation-cap'
    items:
      - name: 'Slack'
        icon: "fa-brands fa-slack"
        subtitle: 'VU slack channel'
        url: 'https://app.slack.com/client/T12H37MFB/C077SJZ3FJ4'
      - name: 'Jira'
        icon: "fa-brands fa-jira"
        subtitle: 'Scrum board for the thesis'
        url: 'https://espoldist.atlassian.net/jira/software/projects/SCRUM/boards/1'

  - name: 'Infra'
    icon: 'fa-solid fa-server'
    items:
      - name: 'Hetzner'
        icon: 'fa-solid fa-server'
        subtitle: 'VPS'
        url: 'https://console.hetzner.cloud/projects'

      - name: 'Grafana'
        icon: 'fa-solid fa-chart-line'
        subtitle: 'Observability monitoring'

      - name: 'Neon'
        icon: 'fa-solid fa-database'
        subtitle: 'Postgres managed database'

      - name: 'Portainer'
        icon: 'fa-solid fa-cubes'
        subtitle: 'Container management'
        url: 'https://containers.frustrated-functor.dev/#!/3/docker/containers'

  - name: 'Blogs'
    icon: 'fa-solid fa-rss'
    items:
      - name: 'Database News'
        icon: 'fa-solid fa-rss'
        subtitle: 'Aggregated news from the database world'
        url: 'https://database.news/'
